apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: blog-hung-mvc
spec:
  serviceName: blog-hung-mvc # Đặt tên cho Headless Service
  replicas: 3
  selector:
    matchLabels:
      app: blog-hung-mvc
  template:
    metadata:
      labels:
        app: blog-hung-mvc
    spec:
      containers:
        - name: blog-hung-mvc
          image: vanhungdev/bloghung:b928a6e6
          ports:
            - containerPort: 5000
  volumeClaimTemplates: # (Phần mới) Khai báo PersistentVolumeClaim mẫu
  - metadata:
      name: blog-hung-data
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 1Gi
