apiVersion: v1
kind: Service
metadata:
  name: service-blog-hung-mvc
spec:
  type: NodePort
  selector:
    app: blog-hung-mvc
  ports:
    - port: 80  # Cổng bên trong cluster
      targetPort: 5000  # Cổng của container ứng dụng
      nodePort: 30088  # Cổng NodePort